---
title: "TPM table for spike-in normalised RNA-seq"
author: "MS"
date: "250124"
output: html_document
file  names should be formatted: 
---
```{r setup}
rm(list=ls())
library(MASS)
library(plotly)
library(broom)
library(corrr)
library(viridis)
library(tidyverse)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) #assumes you're in scripts folder 
load('../../../../shared_code/r_functions/plotting_functions.rda')
```

load TPM data, merge with annotation data, calculate global ratios, recalcualte TPMs for one species and normalise
```{r}
#load data and annotation tables
df1 <- read_tsv("../tables/express-1.5.1.Candida+cerevisiae.2x50mers.TPM_with_both_names.table.txt", show_col_types=FALSE) %>% rename("species"=1, "gene_name"=2, "gene_id"=3)
verified_ORF <- read_tsv("../tables/2230128_verified_ORF.txt", show_col_types=FALSE) %>% dplyr::select(-"species")
annotation <- read_tsv("../tables/210601_gene_annotation.txt", show_col_types=FALSE)
sample_info <- read_tsv("../tables/sample_info.txt", show_col_types=FALSE)

#join dataset to annotation file, filter for genes with TPM > 0 in all samples and pivot TPM longer.
df2 <-  left_join(df1, verified_ORF, by="gene_id") %>% pivot_longer(cols=colnames(dplyr::select(., contains("exp"))), names_to="sample", values_to="TPM")

#get TPM sum for each species, combine with sample info and calculate spike-in ratio, RNA per genome and  RNA per cell
norm_table_1 <- df2 %>% filter(verified_ORF==TRUE) %>% group_by(species, sample) %>% summarise(TPMsum=sum(TPM)) %>% pivot_wider(names_from=species, names_glue="{species}_{.value}", values_from="TPMsum") %>% mutate(spikein_ratio=S_cerevisiae_TPMsum/Candida_TPMsum) %>% left_join(., sample_info, by="sample") %>% mutate(RNA_per_genome=spikein_ratio/DNA_ratio) %>% mutate(RNA_per_cell=RNA_per_genome*DNA_per_cell)

norm_table <- norm_table_1 %>% dplyr::select(sample, sample_short, replicate, experiment, Candida_TPMsum, S_cerevisiae_TPMsum, spikein_ratio , DNA_ratio, mean_cell_volume, RNA_per_genome, RNA_per_cell)

write_tsv(norm_table, file = "../tables/norm_table.txt")

#filter for budding yeast (sc) reads calculate TPM with and without normalisation
df_sc_1 <- left_join(df2, norm_table_1, by="sample") %>% filter(., verified_ORF==TRUE, species == "S_cerevisiae") %>% mutate(TPMsc=((TPM/S_cerevisiae_TPMsum)*10^6)) %>% dplyr::select(-species, -verified_ORF)

df_sum1 <- df_sc_1 %>% group_by(gene_id, exp_group_1) %>% summarise(TPMmean1=mean(TPMsc), TPMmin1=min(TPMsc))
df_sum2 <- df_sc_1 %>% group_by(gene_id, exp_group_2) %>% summarise(TPMmean2=mean(TPMsc), TPMmin2=min(TPMsc))
df_ref1 <- df_sc_1 %>% filter (ref1==TRUE) %>% group_by(gene_id, sample_short) %>% summarise(TPMref1=mean(TPMsc)) %>% rename(sample_ref1=sample_short)
df_ref2 <- df_sc_1 %>% filter (ref2==TRUE)%>% dplyr::select(gene_id, sample_ref2=sample, TPMref2 = TPMsc) 

df_sc <- df_sc_1 %>% left_join(., df_sum1, by=c('gene_id', 'exp_group_1')) %>% left_join(., df_sum2, by=c('gene_id', 'exp_group_2')) %>% left_join(., df_ref1, by=c('sample_ref1', 'gene_id')) %>% left_join(., df_ref2, by=c('sample_ref2', 'gene_id')) %>% mutate(log2TPMnorm1=log2(TPMsc/TPMmean1), log2TPMnorm2 = log2(TPMsc/TPMmean2), log2TPM_FCref1 = log2(TPMsc/TPMref1), log2TPM_FCref2 = log2(TPMsc/TPMref2)) 
```

CDF
```{r}
df_plot <- df_sc %>%filter(TPMmin1>1) %>% dplyr::select(-gene_name) %>% left_join(., annotation, by='gene_id')

p <- df_plot %>% ggplot(aes(x=log2TPM_FCref1, colour=Ho_cluster)) + stat_ecdf(geom = "step", size = 1.2) + facet_wrap(c( ~strain_info, ~condition, ~arrest), ncol=4) +  viridis::scale_colour_viridis(discrete = TRUE, direction=1, option = "mako", begin=0.2, end=0.9, na.value = "grey") + coord_cartesian(xlim=c(-3, 3)) + labs(y= "cumulative fraction", x = "fold change (log2(big/small))")
p
#ggsave(p, filename = "../figures/cfd.svg", dpi = 300, width = 5, height = 4)
```

```{r}
df_export <- df_sc %>%filter(TPMmin1>2) %>% dplyr::select(-gene_name) %>% left_join(., annotation, by='gene_id') %>% filter(Ho_cluster == "iESR cluster") %>% pivot_wider(names_from = c(sample_short), id_cols= c("gene_id", "gene_name"), values_from = log2TPM_FCref1, values_fn=mean)

df_export %>% clipr::write_clip()
```

CORRELATION ANALYASIS
```{r}
#calcualte correlations between selected TPM values, convert to tidy format and plot
df_corr <- df_sc %>% filter(TPMmin1>1) %>% pivot_wider(., id_cols = c("gene_id", "gene_name"), names_from = sample_short, values_from = TPMsc, values_fn = mean)

rcorr_results <- dplyr::select(df_corr, where(is.numeric)) %>% as.matrix() %>% Hmisc::rcorr(type=c("spearman")) 
cor_matrix_r <- rcorr_results$r %>% as.data.frame() %>% rownames_to_column("var1") %>% gather(var2, spearman, -var1)

p <- ggplot(cor_matrix_r, aes(var1, var2, fill=spearman)) + geom_tile() + theme(panel.background = element_blank()) + labs(x="", y="") + viridis::scale_fill_viridis(discrete=FALSE, limits=c(), oob = scales::squish) +  theme(axis.text.x=element_text(angle=90, hjust=1), legend.justification = "top") + coord_fixed(ratio = 1)
p %>% ggplotly()
#ggsave(p, filename = "../../figures/pearson-heatmap_SCD-G1-arrest.svg", dpi = 300, width = 6, height = 4.5)
```

PCA
```{r}
#principle component analysis on all genes with minimum TPM > 5
df_pca <- df_sc %>% filter(exp_group_1=="A" & TPMmin1>1) %>% left_join(., annotation, join_by(gene_id, gene_name)) %>% filter(cell_cycle_low_confidence %>% is.na()) %>% pivot_wider(., id_cols = c("gene_id", "gene_name"), names_from = sample, values_from = "log2TPMnorm1", values_fn = mean)


pca <- df_pca %>% dplyr::select(., where(is.numeric)) %>% prcomp(scale.=FALSE, center=FALSE)

pca_results_variance <- summary(pca)$importance[2,] %>% as.data.frame()
pca_results_samples <- as.data.frame(pca$rotation) %>% rownames_to_column(var="sample") %>% left_join(., sample_info)
pca_results_genes <- bind_cols(dplyr::select(df_pca, gene_id), as.data.frame(pca$x)) 

p <- pca_results_samples %>% ggplot(aes(x=PC1, y=PC2, color=strain_info_condition, text=paste("", sample_short))) + geom_point( size=3, alpha=0.85) +  viridis::scale_color_viridis(discrete=TRUE) #+ coord_fixed(ratio = 1)
p %>% ggplotly()
#ggsave(p, filename = "../../figures/PC1-v-size_SCD-G1-arrest.svg", dpi = 300, width = 6, height = 4.5)
```


plotting
```{r}
df <- df_export %>% filter(TPMmin >5) %>% rowwise()

x <- df$RNA_slope
y <- df$PC1
z <- df$RNA_slope_SE

label<- labs(x= "SCD G1 arrest RNA slope", y= "PC1", color='slope SE') 
axes <- lims(x= c(-2, 2), y = c(-3, 3))

bin_sum <- Hmisc::cut2(x, g=50) %>% bind_cols(., x, y) %>% dplyr::rename("bins"=1,"x"=2,"y"=3) %>% drop_na() %>% dplyr::group_by(bins) %>% summarise(sd=sd(y, na.rm = TRUE), x=mean(x), y=mean(y), n = n())

points <- df %>% geom_point(mapping = aes(x=(x), y=(y), color=(z), text=paste("gene_name:", gene_name)),  size=2, alpha=0.35) 
binned_line <- bin_sum %>% geom_line(mapping = aes(x=(x), y=(y)))
annotate <- annotate(geom = 'text', label =  paste("pearson =", (corrr::correlate(x=x, y=y, method="pearson")$x %>% round(digits = 3))), x=-Inf, y=Inf, hjust=-0.15, vjust=2.5)
color <- scale_color_viridis(begin=0.15, end=1, limits=c(), oob=scales::squish)

p <- ggplot() + points + label + annotate + color + axes + binned_line + coord_fixed(ratio = 2/3)

ggsave(p, filename = "../../figures/RNA-slope-v-PC1_SCD-G1-arrest.svg", dpi = 300, width = 5, height = 4)
```

comparison to 
```{r}
zylstra <- read_tsv("../tables/zylstra2023.txt", show_col_types=FALSE) %>% select(gene_id = "Gene_ID", zylstra_log2FC = log2FoldChange)

df_plot <- df_sc %>% filter(TPMmin2 > 20) %>% filter(arrest =="4.75hr G1 arrest") %>% filter(strain_info =="WT" | strain_info =="Bcy1-AID") %>% filter(condition != "PhIAAlong") %>% pivot_wider(id_cols = gene_id, names_from = strain_info_condition, values_from = log2TPM_FCref2, values_fn = mean)  %>% left_join(., zylstra, join_by(gene_id)) %>% left_join(., annotation) %>% filter(cell_cycle_high_confidence  %>% is.na())

df_plot %>% select(zylstra_log2FC, WT_DMSO, WT_PhIAA, WT_Torin, 'WT_Torin+PhIAA', 'Bcy1-AID_PhIAA') %>% plot_corr2()
  
  #clipr::write_clip()
```





